version: '3.4'
services:
  db:
    image: postgres:9.6
    env_file: .env
    volumes:
      - ./:/workspace
      - pgdata:/var/lib/postgresql/data
  cms:
    # command: ["./docker/new.sh"]
    env_file: .env
    image: registry.gitlab.com/emilioforrer/alex4stars/site:latest
    build:
      context: ./
      target: cms
      args:
        GUID: ${GUID}
        UID: ${UID}
        USER: ${DOCKER_USER}
        STAGE: ${STAGE}
    depends_on:
      - db
    volumes:
      - gems:/home/${DOCKER_USER}/.gem
      - ./:/workspace
      - ./public/media:/workspace/public/media
    ports:
      - "${RAILS_PORT}:${CMS_PORT}"
volumes:
  pgdata:
    driver: local
  redis:
    driver: local
  gems:
    driver: local
